// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSpIr9xrLA8nFwkNI2F2zY10xvkvqGbAs',
    appId: '1:122075754588:web:76184b3af24225a3dc7699',
    messagingSenderId: '122075754588',
    projectId: 'chat-app-a7667',
    authDomain: 'chat-app-a7667.firebaseapp.com',
    storageBucket: 'chat-app-a7667.firebasestorage.app',
    measurementId: 'G-JVRF8EJR8H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwreBcBSFMczZzdhfpwKpAMrQe1rICj84',
    appId: '1:122075754588:android:a1d2ffed692009bbdc7699',
    messagingSenderId: '122075754588',
    projectId: 'chat-app-a7667',
    storageBucket: 'chat-app-a7667.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWeLLdjQuwq_77EHSiAC-oef5R2yDm9PY',
    appId: '1:122075754588:ios:e2d3ba2764703edcdc7699',
    messagingSenderId: '122075754588',
    projectId: 'chat-app-a7667',
    storageBucket: 'chat-app-a7667.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWeLLdjQuwq_77EHSiAC-oef5R2yDm9PY',
    appId: '1:122075754588:ios:e2d3ba2764703edcdc7699',
    messagingSenderId: '122075754588',
    projectId: 'chat-app-a7667',
    storageBucket: 'chat-app-a7667.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSpIr9xrLA8nFwkNI2F2zY10xvkvqGbAs',
    appId: '1:122075754588:web:6ccd15ecf24a9ac9dc7699',
    messagingSenderId: '122075754588',
    projectId: 'chat-app-a7667',
    authDomain: 'chat-app-a7667.firebaseapp.com',
    storageBucket: 'chat-app-a7667.firebasestorage.app',
    measurementId: 'G-CDLR3KZCDE',
  );
}
